version: '3'

services:
  worker:
    build: ./scraper
    # image: &img worker
    image: worker
    command: [/bin/sh , ./starter-script.sh]
    # command: [celery, -A, tasks, worker, --pool=gevent, --concurrency=20, --loglevel=INFO]
    # command: [celery, -A, tasks, worker, --loglevel=INFO]
    # environment: &env
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./scraper:/scraper

  worker2:
    build: ./scraper2
    image: worker2
    command: [/bin/sh , ./starter-script.sh]
    # command: [celery, -A, tasks, worker, --pool=gevent, --concurrency=20, --loglevel=INFO]
    # command: [celery, -A, tasks, worker, --loglevel=INFO]
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./scraper2:/scraper2
  
      
  # Original
  # worker:
  #   build: ./scraper
  #   image: &img worker
  #   command: [celery, -A, tasks, worker, --pool=gevent, --concurrency=20, --loglevel=INFO]
  #   # command: [celery, -A, tasks, worker, --loglevel=INFO]
  #   environment: &env
  #     - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
  #   depends_on:
  #     - rabbitmq
  #   restart: 'no'
  #   volumes: 
  #     - ./scraper:/scraper

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db2


  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
      - ./backend:/app
    environment:
      - MESSAGE_QUEUE=amqp://rabbitmq
    links:
      - rabbitmq
    depends_on:
    - mongo
    - rabbitmq


# Original
  # backend:
  #   build: ./backend
  #   expose:
  #     - "8080"
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./backend:/app
  #   command: [ "nodemon", "app.js" ]
  #   depends_on:
  #   - mongo




  frontend:
    build: ./frontend
    environment:
      - NODE_ENV=development
    expose:
      - "3000"
    ports:
      - '3000:3000'    
    volumes:
      - '${PWD}:/usr/src/app'
      - '/usr/src/app/node_modules'
    links:
      - backend
    command: [ "npm", "start" ]
    depends_on:
    - backend
    - mongo

  rabbitmq:
    image: rabbitmq:3.7.4

volumes:
  data-volume:
